# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-tutorial',
                'doc_host': 'https://cgrinaldi.github.io',
                'git_url': 'https://github.com/cgrinaldi/nbdev-tutorial',
                'lib_path': 'nbdev_tutorial'},
  'syms': { 'nbdev_tutorial.core': {'nbdev_tutorial.core.add': ('math.html#add', 'nbdev_tutorial/core.py')},
            'nbdev_tutorial.math': { 'nbdev_tutorial.math.add': ('math.html#add', 'nbdev_tutorial/math.py'),
                                     'nbdev_tutorial.math.multiply': ('math.html#multiply', 'nbdev_tutorial/math.py')}}}
