# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_math.ipynb.

# %% auto 0
__all__ = ['add', 'multiply']

# %% ../nbs/00_math.ipynb 4
def add(a, b):
    """Add two numbers."""
    return a + b

# %% ../nbs/00_math.ipynb 9
def multiply(a, b):
    """Multiply two numbers."""
    return a * b
